### ISSUE TITLE
Docforge File system handler fails to resolve documentation manifest that are not in cwd when using nodesSelector  

### ISSUE THREAD

**Issue by swilen-iwanow** [gardener/docforge#113]
**What happened**:
With the manifest.yaml 

```
nodesSelector:
  path: module.yaml
```
and filesystem structure 
- c
  |  - manifest.yaml
  |  - module.yaml

Docforge fails to find module.yaml because it is not in the cwd
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**How to categorize this issue?**

/kind bug
/priority normal

**Comment by Kristian-ZH** [comment]
The fail-system handler is not supported anymore

/close
