### ISSUE TITLE
Maintain valid absolute links to tree objects when rewriting them

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#15]
**What happened**:
When converting GitHub document links to absolute for indexing, we always assume blobs but in practice a link can have a tree object as destination, turning it to invalid one when it is necessary to serialize the absolute link in the document.

**What you expected to happen**:
Maintain valid absolute links.

Test with: 
- [charts](https://github.com/gardener/gardener/tree/master/charts)
- [example](https://github.com/gardener/gardener/tree/master/example)

**Comment by g-pavlov** [comment]
@swilen-iwanow Can you check if this is still an issue and eventually close?

**Comment by swilen-iwanow** [comment]
Yes it is :D
