### ISSUE TITLE
Specify arguments to `--hugo-section-files` as regular expressions/globs

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#155]
**What would you like to be added**:
Specify arguments to `--hugo-section-files` as regular expressions/globs

**Why is this needed / describe a real-world scenario**:
It is more efficient to specify a family of files compliant as a pattern to which they comply rather than iterate the exact ones as the only option to specify section file candidates with the `--hugo-section-files`  falg

**How to categorize this?**:

/kind enhancement
/priority normal

**Comment by Kristian-ZH** [comment]
Not currently in the backlog

/close
