### ISSUE TITLE
Change --github-info-destination from relative to any path

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#156]
**What would you like to be added**:
It must be possible to set absolute path as argument of `--github-info-destination` 

**Why is this needed / describe a real-world scenario**:
Any argument specified to that flag ends up relatively resolved to the destination folder. Normally that would be fine from docforge perspective, but we are talking a hugo-specific module here so we need to consider the context. The jsons generated by the flag need to end up in hugo's data module folder, which is configurable and defaults to `data`. Therefore we need to be flexible to push this content to a folder outside the destination (hugo's `content` in this case). The goal is achievable using relative paths indeed, going one level up (`../data`). However, it's is only more natural to consider this as an option alongside with the ability to provide absolute path that is considered as is.

**How to categorize this?**:

/kind enhancement
/priority normal

**Comment by Kristian-ZH** [comment]
This is not present in our backlog.
We will get back to this issue if we find a usecase with it

/close
