### ISSUE TITLE
Implement depth filter for filesystem nodesSelector

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#161]
**What would you like to be added**:
Filter depth for for filesystem `nodesSelector` similar to the same in the GitHub `nodesSelector` implementation

**Why is this needed / describe a real-world scenario**:
The file system api implementation needs to be on par with the GitHub one.

**How to categorize this?**:
/kind enhancement
/priority normal

**Comment by Kristian-ZH** [comment]
This is not present in the backlog currently
If we find a usecase for this issue we will get back on it

/close
