### ISSUE TITLE
Addressing versions in document cross-repository/component links 

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#17]
Relative links in source documents are resolved to absolute and that will set their version to the same as the linking document.
Absolute links to other nodes in the same repository (that should be relative) that feature a specific version may do that on purpose (to pin to exact state) or as a result of bad practices. 

Absolute links to another repository are normally using its master. As development progresses it may turn out that an older version of a linking document is pointing to a different, updated state of the master version of the linked document. This does not reflect consistently the state of the product for a particular version. 

To resolve this, the older version of the document should be updated to link to a valid state of the linked document to keep the common information space consistent for that version. Or even better that should happen upon release to have all links to master versions changed with the respective component versions. 

Another approach would be to manage the created bundles versioned in a repo too but that will not enable reproducible builds for a particular version of the whole product.

Managing this manually can be an overkill and should be aided by automation if that's what's necessary to happen. We need to further discuss the following options:
1. If the absolute link version doesn't match a node, then keep the original link 
1. If the absolute link points a node, update absolute link with the version of the document representing the node (e.g. master -> 1.8.0).
1. Do not mandate an approach but make it configurable (either of the above) e.g. using semver format to instruct behavior per node or globally

**Comment by g-pavlov** [comment]
Documented in: 
- https://github.com/gardener/docforge/blob/master/docs/consistency.md
- https://github.com/gardener/docforge/blob/master/docs/versions.md

**Comment by Kristian-ZH** [comment]
/close

Not a relevant usecase anymore
