### ISSUE TITLE
Absolute links are not not built properly

### ISSUE THREAD

**Issue by dimitar-kostadinov** [gardener/docforge#194]
**What happened**:

Markdown links that points to repository root are no properly build as absolute links, e.g. 
"/docs/aws-route53/README.md" is resolved to "https://github.com/docs/aws-route53/README.md"

**What you expected to happen**:

The link should be properly build, e.g. "https://github.com/gardener/external-dns-management/blob/master/docs/aws-route53/README.md"

**How to categorize this issue?**

/kind bug
/priority normal

**Comment by JordanJordanov** [comment]
Duplicates  https://github.com/gardener/docforge/issues/193
