### ISSUE TITLE
Documentation Source Processors

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#20]
There are a number of tasks that could be performed on a markdown source prior to building it into deployable bundle with tools such as Hugo.

Regardless of the tool that will build the markdown source it is very helpful to be able to keep source minimal and autogenerate and process certain parts of according to some globally defined rules. This epic aims at delivering a set of standalone tasks that can do that for various aspects. Those tools will be applied and validated in the Gardener project but will be generally applicable in the context of delivering *documentation-as-code*.

The list can expand base don popular demand. A reasonable starter set is:

- **Image processor**
  The image processor uses embedded (raster) images as template to create web content that is considerate about its environment and deliver images with sizes that are applicable to the requesting device to save bandwidth and improve user experience.
  - Processes images embedded in a document converting them to HTML `<img>` tag with `srcset` attribute. 
  - Processes the images to generate downsized variants, considering the supplied image as the most high-resolution one, and link them in the corresponding `srcset` attributes. The supported dimensions are configurable.
  - The generated images that are large enough, are generated with progressive rendering. 
  - Converts images to a single format which is a configurable option

- **Fenced code block processor**
  Fenced code can be inline, but with the help of a tool can also be imported from a file at build time. That is a particular advantage if it's part of the source code, if the source is a snippet reused across several documents, and because having it out-of-document enables the language-specific tools to act on it as on any source code. Standard markdown does not support anything but inline code. A specific markup that the tool can process is required:
Two options are to use structured comment or standard link markdown with attributes support that will be parsed by a custom markdown parser.
For source code snippets, it is particularly handy to be able to specify a range that is obtained from a source file and displayed as fenced code block. It would be useful to use GitHub's way to specify range in a file (#LX-LY, where X is starting line and Y is end line of the range) along the file location link.

**Comment by Kristian-ZH** [comment]
After the refactoring this is not a relevant anymore
/close
