### ISSUE TITLE
Enhance document nodes to support a wide range of valid file formats

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/docforge#322]
**What would you like to be added**:
Currently documents nodes only support `md` formatted files. I would like it to work with valid file formats such as `html`, `xhtml`, `xml`, `txt`, etc.

**Why this is needed? **:
`diki` reports are in html format and shall be part of the site structure.

**How to categorize this?**:

/kind enhancement
/priority 3

**Comment by Kostov6** [comment]
Let's generalise this like this: Valid page file extensions to be customisable. WDYT?

**Comment by AleksandarSavchev** [comment]
> Let's generalise this like this: Valid page file extensions to be customisable. WDYT?

Edited the issue to add your suggestion

**Comment by Kostov6** [comment]
From the unexpected problem caught by https://github.com/gardener/docforge/pull/352 let's rethink some points:
- Conceptually `Registry` and `repositoryhost.Interface` should represent a repo which can be operated by `Tree` and `Read`. So it doesn't make sense to have any special parsing like`ParsingOptions`. This includes `ExtractedFilesFormats`. This allows us to not have to add media file extensions to `ExtractedFilesFormats` which was a main driver to the unexpected problem.
- Let's do all the filtering when we construct the manifest. This means in `manifest.go`
- Let's leave the following as it is
https://github.com/gardener/docforge/blob/918e4442384129634040348f44ee5c5c39104fda/cmd/app/flags.go#L71-L73

Lets create a new branch with the following subtasks:

1. Add a step `checkFileTypeFormats` that is between `resolveRelativeLinks` and `extractFilesFromNode`. It checks if all the fields of `FileType` have extension that is part of the. `ResolveManifest` and `nodeTransformation` should be adapted to have `ContentFileFormats`(rename of `ExtractedFilesFormats`) parameter. After that let's adapt `constructNodeTree` to filter out files not part of `ContentFileFormats`.
2. Drop `github_http_cache.go@ParsingOptions`
3. Parse only `md` files (reuse changes to `pkg/workers/document/document_worker.go` from the pull request above and its unit test)
