### ISSUE TITLE
Interrupting the program yields `panic: send on closed channel`

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#61]
**What happened**:
Interrupting the program yields `panic: send on closed channel`

**What you expected to happen**:
Interrupt silently

**How to reproduce it (as minimally and precisely as possible)**:
Run a build with docforge and hit ctrl+C (or the Mac analogue) before it ends

**Comment by Kristian-ZH** [comment]
This issue does not present anymore

/close
