### ISSUE TITLE
Propagate 'not found' errors context

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#97]
**What would you like to be added**:
Currently an incorrect resource name (with correct path) yields a warning log entry but the final error says "not found" without any context to find out the the reason at a glance. 

**Why is this needed / describe a real-world scenario**:
Finding out which resource name needs to be corrected.

**How to categorize this?**:
/kind enhancement
/priority normal

**Comment by Kristian-ZH** [comment]
After the refactoring, this is no more relevant

/close
