### ISSUE TITLE
Fix silent 'not found' errors 

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#98]
**What would you like to be added**:
This [PR](https://github.com/gardener/docforge/pull/89) fixes silent errors when document node source's resource name is wrong. Same fix is necessary also for `ContentSelector.Source`, `Template.Path` and `NodeSelector.Path`.

**Why is this needed / describe a real-world scenario**:
Find out the reason for files that fail to download in that case.

**How to categorize this?**:

/kind enhancement
/priority normal

**Comment by Kristian-ZH** [comment]
Not relevant after the refactoring

/close
